import 'dart:convert';
import 'package:http/http.dart' as http;

class GeminiApi{

  // Creating a header
  static Future<Map<String, String>> getHeader() async{

    return{

      "Content-Type":"application/json",

    };

  }

  // Now lets create a http request
  static Future<String> getGeminiData(message) async{

    try{

      final header = await getHeader();

      final Map<String, dynamic> requestBody = {

        "contents": [

          {

            'parts':[

              {

                'text': 'user message request here $message',

              }

            ]

          }

        ],

        'generationConfig':{

          'temperature': 0.8,
          'maxOutputTokens':1000 // its max token to generate result

         }

      };

      String url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.0-pro:generateContent?key=AIzaSyAIxhLd-QYlqHoB5k1ocZPf6UsN42DvgwE";

      var response = await http.post(
        Uri.parse(url),
        headers: header,
        body: jsonEncode(requestBody)
      );


      if(response.statusCode == 200){

        var jsonResponse = jsonDecode(response.body) as Map<String, dynamic>;
        return jsonResponse['candidates'][0]['content']['parts'][0]['text'];
        // This will returns the result generated by gemini

      }else{

        return '';

      }

    }catch(e){

      // print("Error $e");
      return '';

    }

  }

}