// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAikElAIWS9JPLV80S7HMnt98OXIrn9Mqw',
    appId: '1:655704394201:web:0fb1c1f2585205d6c9f1c8',
    messagingSenderId: '655704394201',
    projectId: 'medical-records-809e6',
    authDomain: 'medical-records-809e6.firebaseapp.com',
    storageBucket: 'medical-records-809e6.appspot.com',
    measurementId: 'G-XJTSKCX97Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWbi2eNJgytFeVSZFnpW4X6LjYLvLYko8',
    appId: '1:655704394201:android:03e1925d26300b17c9f1c8',
    messagingSenderId: '655704394201',
    projectId: 'medical-records-809e6',
    storageBucket: 'medical-records-809e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf_Jh0YiX7cE5iq3kpjR3hpT37syst-E4',
    appId: '1:655704394201:ios:80b1e486291d272ac9f1c8',
    messagingSenderId: '655704394201',
    projectId: 'medical-records-809e6',
    storageBucket: 'medical-records-809e6.appspot.com',
    iosBundleId: 'com.HealSnap.healSnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf_Jh0YiX7cE5iq3kpjR3hpT37syst-E4',
    appId: '1:655704394201:ios:8481dbbf7ed0baaec9f1c8',
    messagingSenderId: '655704394201',
    projectId: 'medical-records-809e6',
    storageBucket: 'medical-records-809e6.appspot.com',
    iosBundleId: 'com.HealSnap.healSnap.RunnerTests',
  );
}
